apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: claim-volume-storage-class
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: storage-class-default