apiVersion: v1
kind: PersistentVolume
metadat:
  name: pv-nfs-storage
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWirteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /dir/path/on/nfs/server
    server: nfs-server-ip-address